services:
  - type: web
    name: trendface-live-app
    runtime: static
    buildCommand: npm ci && npm run build -- --configuration production
    staticPublishPath: dist/trendface/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
